CREATE DATABASE RAD_APP;

DROP TABLE IF EXISTS RAD_APP.RD_ROLE;
CREATE TABLE RAD_APP.RD_ROLE (
	ROLE_DID		BIGINT(20) NOT NULL,
	DESCRIPTION		VARCHAR(255) NULL DEFAULT NULL,
	ROLE_NAME		VARCHAR(255) NULL DEFAULT NULL,
	STATUS			INT(11) NULL DEFAULT NULL,
	CREATE_DATE		TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ROLE_DID)
) ENGINE = INNODB;

DROP TABLE IF EXISTS RAD_APP.RD_USER;
CREATE TABLE RAD_APP.RD_USER (
	USER_DID BIGINT(20) NOT NULL,
	FIRST_NAME VARCHAR(255) NULL DEFAULT NULL,
	GENDER CHAR(1) NULL DEFAULT NULL,
	LAST_NAME VARCHAR(255) NULL DEFAULT NULL,
	MIDDLE_NAME VARCHAR(255) NULL DEFAULT NULL,
	CREATE_DATE		TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (USER_DID)
) ENGINE = INNODB;

DROP TABLE IF EXISTS RAD_APP.RD_USER_ROLE;
CREATE TABLE RAD_APP.RD_USER_ROLE (
	USER_DID BIGINT(20) NOT NULL,
	ROLE_DID BIGINT(20) NOT NULL,
	CREATE_DATE		TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (USER_DID, ROLE_DID),
	INDEX FK_USERDID_CGUR (USER_DID),
	INDEX FK_ROLEDID_CGUR (ROLE_DID),
	FOREIGN KEY (USER_DID) REFERENCES RAD_APP.RD_USER (USER_DID) ON DELETE CASCADE,
	FOREIGN KEY (ROLE_DID) REFERENCES RAD_APP.RD_ROLE (ROLE_DID) ON DELETE CASCADE
) ENGINE = INNODB;

DROP TABLE IF EXISTS RAD_APP.RD_LOGIN;
CREATE TABLE RAD_APP.RD_LOGIN (
	USER_DID 		BIGINT(20) NOT NULL,
	LAST_LOGIN		DATETIME NULL DEFAULT NULL,
	PASSWORD		VARCHAR(255) NULL DEFAULT NULL,
	STATUS			INT(11) NULL DEFAULT NULL,
	USERNAME		VARCHAR(255) NULL DEFAULT NULL,
	CREATE_DATE		TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (USER_DID),
	INDEX FK_USERDID_CGL (USER_DID),
	FOREIGN KEY (USER_DID) REFERENCES RAD_APP.RD_USER (USER_DID) ON DELETE CASCADE
) ENGINE = INNODB;





-- FOR SUPER USER
INSERT INTO RAD_APP.RD_ROLE (ROLE_DID, ROLE_NAME, DESCRIPTION, STATUS) VALUES (1, 'ROLE_ADMIN', 'ADMINISTRATIVE ROLE', 1, 0);
INSERT INTO RAD_APP.RD_ROLE (ROLE_DID, ROLE_NAME, DESCRIPTION, STATUS) VALUES (2, 'ROLE_USER', 'USER ACCESS WITH CERTAIN PREVILEGES', 1, 0);
INSERT INTO RAD_APP.RD_ROLE (ROLE_DID, ROLE_NAME, DESCRIPTION, STATUS) VALUES (3, 'ROLE_VISITOR', 'ALLOWED ONLY FOR READ ONLY CONTENT', 1, 0);
COMMIT;

INSERT INTO RAD_APP.RD_USER (USER_DID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER) VALUES (1, 'SUPER USER', 'SUPER USER', 'SUPER USER', 'M', 0);
COMMIT;

INSERT INTO RAD_APP.RD_LOGIN(USER_DID, USERNAME, PASSWORD, STATUS, LAST_LOGIN) 
VALUES (1, 'super', '$2a$10$g6i0LyEs.srO/5etCeKhYuQOPKOXs1xqTMznOfPUFtk0hyrYiHBkm', 1, CURRENT_TIMESTAMP, 0);
COMMIT;

INSERT INTO RAD_APP.RD_USER_ROLE (USER_DID, ROLE_DID) VALUES (1, 1);
INSERT INTO RAD_APP.RD_USER_ROLE (USER_DID, ROLE_DID) VALUES (1, 2);
COMMIT;

ALTER TABLE RAD_APP.RD_USER MODIFY COLUMN USER_DID BIGINT(20) AUTO_INCREMENT;
ALTER TABLE RAD_APP.RD_ROLE MODIFY COLUMN ROLE_DID BIGINT(20) AUTO_INCREMENT;

ALTER TABLE RAD_APP.RD_USER ADD COLUMN VERSION BIGINT(10);
ALTER TABLE RAD_APP.RD_ROLE ADD COLUMN VERSION BIGINT(10);
ALTER TABLE RAD_APP.RD_LOGIN ADD COLUMN VERSION BIGINT(10);