CREATE DATABASE RAD_APP;
USE RAD_APP;

DROP TABLE IF EXISTS RAD_APP.RD_ROLE;
CREATE TABLE RAD_APP.RD_ROLE (
	ROLE_DID		BIGINT(20) NOT NULL,
	DESCRIPTION		VARCHAR(255) NULL DEFAULT NULL,
	ROLE_NAME		VARCHAR(255) NULL DEFAULT NULL,
	STATUS			INT(11) NULL DEFAULT NULL,
	CREATE_DATE		TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ROLE_DID)
) ENGINE = INNODB;

DROP TABLE IF EXISTS RAD_APP.RD_USER;
CREATE TABLE RAD_APP.RD_USER (
	USER_DID BIGINT(20) NOT NULL,
	FIRST_NAME VARCHAR(255) NULL DEFAULT NULL,
	GENDER CHAR(1) NULL DEFAULT NULL,
	LAST_NAME VARCHAR(255) NULL DEFAULT NULL,
	MIDDLE_NAME VARCHAR(255) NULL DEFAULT NULL,
	CREATE_DATE		TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (USER_DID)
) ENGINE = INNODB;

DROP TABLE IF EXISTS RAD_APP.RD_USER_ROLE;
CREATE TABLE RAD_APP.RD_USER_ROLE (
	USER_DID BIGINT(20) NOT NULL,
	ROLE_DID BIGINT(20) NOT NULL,
	CREATE_DATE		TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (USER_DID, ROLE_DID),
	INDEX FK_USERDID_CGUR (USER_DID),
	INDEX FK_ROLEDID_CGUR (ROLE_DID),
	FOREIGN KEY (USER_DID) REFERENCES RAD_APP.RD_USER (USER_DID) ON DELETE CASCADE,
	FOREIGN KEY (ROLE_DID) REFERENCES RAD_APP.RD_ROLE (ROLE_DID) ON DELETE CASCADE
) ENGINE = INNODB;

DROP TABLE IF EXISTS RAD_APP.RD_LOGIN;
CREATE TABLE RAD_APP.RD_LOGIN (
	USER_DID 		BIGINT(20) NOT NULL,
	LAST_LOGIN		DATETIME NULL DEFAULT NULL,
	PASSWORD		VARCHAR(255) NULL DEFAULT NULL,
	STATUS			INT(11) NULL DEFAULT NULL,
	USERNAME		VARCHAR(255) NULL DEFAULT NULL,
	CREATE_DATE		TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (USER_DID),
	INDEX FK_USERDID_CGL (USER_DID),
	FOREIGN KEY (USER_DID) REFERENCES RAD_APP.RD_USER (USER_DID) ON DELETE CASCADE
) ENGINE = INNODB;



-- FOR SUPER USER
INSERT INTO RAD_APP.RD_ROLE (ROLE_DID, ROLE_NAME, DESCRIPTION, STATUS) VALUES (1, 'ROLE_ADMIN', 'ADMINISTRATIVE ROLE', 1, 0);
INSERT INTO RAD_APP.RD_ROLE (ROLE_DID, ROLE_NAME, DESCRIPTION, STATUS) VALUES (2, 'ROLE_USER', 'USER ACCESS WITH CERTAIN PREVILEGES', 1, 0);
INSERT INTO RAD_APP.RD_ROLE (ROLE_DID, ROLE_NAME, DESCRIPTION, STATUS) VALUES (3, 'ROLE_VISITOR', 'ALLOWED ONLY FOR READ ONLY CONTENT', 1, 0);
COMMIT;

INSERT INTO RAD_APP.RD_USER (USER_DID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, GENDER) VALUES (1, 'SUPER USER', 'SUPER USER', 'SUPER USER', 'M', 0);
COMMIT;

INSERT INTO RAD_APP.RD_LOGIN(USER_DID, USERNAME, PASSWORD, STATUS, LAST_LOGIN) 
VALUES (1, 'super', '$2a$10$g6i0LyEs.srO/5etCeKhYuQOPKOXs1xqTMznOfPUFtk0hyrYiHBkm', 1, CURRENT_TIMESTAMP, 0);
COMMIT;

INSERT INTO RAD_APP.RD_USER_ROLE (USER_DID, ROLE_DID) VALUES (1, 1);
INSERT INTO RAD_APP.RD_USER_ROLE (USER_DID, ROLE_DID) VALUES (1, 2);
COMMIT;

ALTER TABLE RAD_APP.RD_USER MODIFY COLUMN USER_DID BIGINT(20) AUTO_INCREMENT;
ALTER TABLE RAD_APP.RD_ROLE MODIFY COLUMN ROLE_DID BIGINT(20) AUTO_INCREMENT;

ALTER TABLE RAD_APP.RD_USER ADD COLUMN UPDATE_DATE TIMESTAMP NULL;
ALTER TABLE RAD_APP.RD_USER ADD COLUMN STATUS INT(11) DEFAULT 0;
ALTER TABLE RAD_APP.RD_LOGIN ADD COLUMN UPDATE_DATE TIMESTAMP NULL;

ALTER TABLE RAD_APP.RD_USER ADD COLUMN VERSION BIGINT(10);
ALTER TABLE RAD_APP.RD_ROLE ADD COLUMN VERSION BIGINT(10);
ALTER TABLE RAD_APP.RD_LOGIN ADD COLUMN VERSION BIGINT(10);


DROP TABLE IF EXISTS RAD_APP.RDX_CONTACT_TYPE;
CREATE TABLE RAD_APP.RDX_CONTACT_TYPE (
	TYPE_DID		INTEGER(10) NOT NULL,
	TYPE			VARCHAR(50) NOT NULL,
	STATUS			TINYINT(2) NOT NULL,
	PRIMARY KEY (TYPE_DID)
) ENGINE = INNODB;

DROP TABLE IF EXISTS RAD_APP.RD_CONTACT;
CREATE TABLE RAD_APP.RD_CONTACT (
	CONTACT_DID		BIGINT(20) NOT NULL,
	USER_DID 		BIGINT(20) NOT NULL,
	TYPE_DID		INTEGER(10) NOT NULL,
	CONTACT_VALUE	VARCHAR(255) NOT NULL,
	IS_DEFAILT		TINYINT(2) DEFAULT NULL,
	STATUS			TINYINT(2) NOT NULL,
	CREATE_DATE		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	VERSION 		INTEGER(10),
	PRIMARY KEY (CONTACT_DID),
	INDEX FK_USERDID_CGC (USER_DID),
	INDEX FK_TYPEDID_CGC (TYPE_DID),
	FOREIGN KEY (USER_DID) REFERENCES RAD_APP.RD_USER (USER_DID) ON DELETE CASCADE,
	FOREIGN KEY (TYPE_DID) REFERENCES RAD_APP.RDX_CONTACT_TYPE (TYPE_DID) ON DELETE CASCADE
) ENGINE = INNODB;

INSERT INTO RAD_APP.RDX_CONTACT_TYPE (TYPE_DID, TYPE, STATUS) VALUES(1, "EMAIL-PERSONAL", 1);
INSERT INTO RAD_APP.RDX_CONTACT_TYPE (TYPE_DID, TYPE, STATUS) VALUES(2, "EMAIL-OFFICE", 1);
INSERT INTO RAD_APP.RDX_CONTACT_TYPE (TYPE_DID, TYPE, STATUS) VALUES(3, "MOBILE-PERSONAL", 1);
INSERT INTO RAD_APP.RDX_CONTACT_TYPE (TYPE_DID, TYPE, STATUS) VALUES(4, "MOBILE-OFFICE", 1);
INSERT INTO RAD_APP.RDX_CONTACT_TYPE (TYPE_DID, TYPE, STATUS) VALUES(5, "LANDLINE-PERSONAL", 1);
INSERT INTO RAD_APP.RDX_CONTACT_TYPE (TYPE_DID, TYPE, STATUS) VALUES(6, "LANDLINE-OFFICE", 1);
INSERT INTO RAD_APP.RDX_CONTACT_TYPE (TYPE_DID, TYPE, STATUS) VALUES(7, "ADDRESS-PERSONAL", 1);
INSERT INTO RAD_APP.RDX_CONTACT_TYPE (TYPE_DID, TYPE, STATUS) VALUES(8, "ADDRESS-OFFICE", 1);
INSERT INTO RAD_APP.RDX_CONTACT_TYPE (TYPE_DID, TYPE, STATUS) VALUES(9, "FAX-PERSONAL", 1);
INSERT INTO RAD_APP.RDX_CONTACT_TYPE (TYPE_DID, TYPE, STATUS) VALUES(10, "FAX-OFFICE", 1);
COMMIT;

ALTER TABLE RAD_APP.RD_USER MODIFY COLUMN VERSION INTEGER(10);
ALTER TABLE RAD_APP.RD_ROLE MODIFY COLUMN VERSION INTEGER(10);
ALTER TABLE RAD_APP.RD_LOGIN MODIFY COLUMN VERSION INTEGER(10);

ALTER TABLE RAD_APP.RD_USER MODIFY COLUMN STATUS TINYINT(2);
ALTER TABLE RAD_APP.RD_ROLE MODIFY COLUMN STATUS TINYINT(2);
ALTER TABLE RAD_APP.RD_LOGIN MODIFY COLUMN STATUS TINYINT(2);

ALTER TABLE RAD_APP.RD_CONTACT MODIFY COLUMN CONTACT_DID BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE RAD_APP.RD_CONTACT AUTO_INCREMENT=1;

ALTER TABLE RAD_APP.RD_CONTACT ADD COLUMN UPDATE_DATE TIMESTAMP NULL;