CREATE DATABASE RAD_AUTH;

DROP TABLE IF EXISTS RAD_AUTH.OAUTH_CLIENT_DETAILS;
CREATE TABLE RAD_AUTH.OAUTH_CLIENT_DETAILS 
(
  	CLIENT_ID 				VARCHAR(256) PRIMARY KEY,
  	RESOURCE_IDS 			VARCHAR(256),
  	CLIENT_SECRET 			VARCHAR(256),
  	SCOPE 					VARCHAR(256),
  	AUTHORIZED_GRANT_TYPES 	VARCHAR(256),
  	WEB_SERVER_REDIRECT_URI VARCHAR(256),
  	AUTHORITIES 			VARCHAR(256),
  	ACCESS_TOKEN_VALIDITY 	INTEGER,
  	REFRESH_TOKEN_VALIDITY 	INTEGER,
  	ADDITIONAL_INFORMATION 	VARCHAR(4096),
  	AUTOAPPROVE 			VARCHAR(256)
);

DROP TABLE IF EXISTS RAD_AUTH.OAUTH_CLIENT_TOKEN;
CREATE TABLE RAD_AUTH.OAUTH_CLIENT_TOKEN (
	TOKEN_ID 			VARCHAR(255),
	TOKEN 				BLOB,
	AUTHENTICATION_ID 	VARCHAR(255),
	USER_NAME 			VARCHAR(255),
	CLIENT_ID 			VARCHAR(255)
);

DROP TABLE IF EXISTS RAD_AUTH.OAUTH_ACCESS_TOKEN;
CREATE TABLE RAD_AUTH.OAUTH_ACCESS_TOKEN (
	TOKEN_ID 			VARCHAR(255),
	TOKEN 				BLOB,
	AUTHENTICATION_ID 	VARCHAR(255),
	USER_NAME 			VARCHAR(255),
	CLIENT_ID 			VARCHAR(255),
	AUTHENTICATION 		BLOB,
	REFRESH_TOKEN 		VARCHAR(255)
);

DROP TABLE IF EXISTS RAD_AUTH.OAUTH_REFRESH_TOKEN;
CREATE TABLE RAD_AUTH.OAUTH_REFRESH_TOKEN (
	TOKEN_ID 		VARCHAR(255),
	TOKEN 			BLOB,
	AUTHENTICATION 	BLOB
);

DROP TABLE IF EXISTS RAD_AUTH.OAUTH_CODE;
CREATE TABLE RAD_AUTH.OAUTH_CODE (
	CODE 			VARCHAR(255), 
	AUTHENTICATION 	BLOB
);

ALTER TABLE RAD_AUTH.OAUTH_CLIENT_DETAILS ADD CREATE_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE RAD_AUTH.OAUTH_CLIENT_TOKEN ADD CREATE_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE RAD_AUTH.OAUTH_ACCESS_TOKEN ADD CREATE_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE RAD_AUTH.OAUTH_REFRESH_TOKEN ADD CREATE_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE RAD_AUTH.OAUTH_CODE ADD CREATE_DATE TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;


-- insert client details
-- $2a$10$Dif6l0q.O4mGqG0J49xkXeNoK.U.BH.BByRHUEd38VdnebpEU6f4a = R1$_sYstEM
INSERT INTO RAD_AUTH.OAUTH_CLIENT_DETAILS 
	(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY)
VALUES
	('rad_system', 'rduserportal', '$2a$10$Dif6l0q.O4mGqG0J49xkXeNoK.U.BH.BByRHUEd38VdnebpEU6f4a', 'read,write', 'password,refresh_token,client_credentials,authorization_code', 
	'ROLE_RAD_AUTH_SUPER', 600, 21600);
COMMIT;
